### PR TITLE
Makes this repository pip installable

### PR DESCRIPTION
**Pull request by asemic-horizon**
With these two files this repository can be installed with `pip install git+https://github.com/Kodiologist/Kodhy.git` or added to a project's `requirements.txt`.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looks good, thanks. I don't think pytest is a requirement since you only need it to run the tests, and they're not run automatically, but I'm not super familiar with Python packaging conventions.

**Comment by Kodiologist** [comment]
I think you made a mistake in the commit structure. GitHub now thinks you want to add 356 lines and delete 1,270. Try rebasing all your changes into one commit.

**Comment by asemic-horizon** [comment]
With a subsequent change? Yes, it got all messed up. I had tried to merge your subsequent changes making a mess of everything. Then I was having weird problems with module namespaces and changed filenames to "kodhy-master"/"kodhy-utils" (and references within) as a stopgap measure to keep working (*with* the kodhy tooks but not *on* them, at least yet).

Basically I made a huge mess; but since I didn't try to make a PR, I didn't think changes to the fork would affect your repository. 

What would be the proper github form and/or etiquette if I wanted to make a fork that could diverge from the original (e.g. possibly breaking functionality, etc.) *without* disturbing you or expecting you to accept my changes? Should I refrain from prematurely pushing to Github?

**Comment by asemic-horizon** [comment]
Oh man. Was my entire repository attached to this pull request somehow? I have to scrap that and maybe consider working on an "air-gapped" local version. Please reject all of this; I'm very sorry.

**Pull request closed without merging**
